name: CI

on: pull_request

jobs:
  build:
    name: Build, Test, and Format
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run build
    - run: npm run format
    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_author_email: pmarsceill@github.com
        commit_author_name: Patrick Marsceill
        commit_message: 🎨 Prettier
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
