name: Node.js CI

on:
  push:
    branches: [master]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: Prettier Action
      uses: creyD/prettier_action@v2.0
      with:
        # Commit message
        commit_message: 🎨Prettier
        # Options for the 'prettier' command
        prettier_options: --write \"**/*.{js,jsx,json,md}\"
        # Branch which the changes are merged to
        branch: master
