name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * 5"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This Issue is being marked as stale due to lack of activity for 60 days.'
        stale-pr-message: 'This Pull Request is being marked as stale due to lack of activity for 60 days.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
